name: Bug Report
description: Report a bug or unexpected behavior in AppWhistler
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees:
  - aresforblue-ai
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below with as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of AppWhistler is affected?
      options:
        - Backend API
        - Frontend UI
        - GraphQL
        - AI Fact Checker
        - Blockchain Integration
        - Database
        - Scraper
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - Application crashes or data loss
        - High - Major functionality broken
        - Medium - Feature partially broken
        - Low - Minor issue or cosmetic
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, macOS 13, Windows 11]
        - Node Version: [e.g., 18.17.0]
        - npm Version: [e.g., 9.6.7]
        - Browser: [e.g., Chrome 120, Firefox 121, Safari 17]
        - AppWhistler Version: [e.g., 0.1.0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs/Screenshots
      description: Add any error messages, logs, or screenshots that help explain the problem
      placeholder: Paste logs or drag and drop images here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem (e.g., happens only on certain data, intermittent, etc.)

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have included all requested information above
          required: true
        - label: I have tested this with the latest version
          required: false
