name: Security Vulnerability Report
description: Report a security vulnerability (use privately if sensitive)
title: "[Security]: "
labels: ["security", "needs-triage"]
assignees:
  - aresforblue-ai
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: If this is a sensitive security vulnerability, please DO NOT submit it here. 
        Instead, use GitHub's Security Advisory feature or email security@appwhistler.com directly.
        
        See our [Security Policy](https://github.com/aresforblue-ai/appwhistler/blob/main/SECURITY.md) for details.

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm this is not a sensitive vulnerability
      options:
        - label: This is NOT a sensitive security issue (no active exploit, not publicly disclosed)
          required: true
        - label: I have read the Security Policy
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this vulnerability?
      options:
        - Critical - Immediate threat (remote code execution, data breach)
        - High - Serious threat (authentication bypass, privilege escalation)
        - Medium - Moderate threat (XSS, CSRF)
        - Low - Minor threat (information disclosure)
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Vulnerability Type
      description: What type of vulnerability is this?
      options:
        - SQL Injection
        - Cross-Site Scripting (XSS)
        - Cross-Site Request Forgery (CSRF)
        - Authentication Bypass
        - Authorization Issues
        - Remote Code Execution
        - Denial of Service
        - Information Disclosure
        - Insecure Dependencies
        - Configuration Issues
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the vulnerability in detail
      placeholder: The application is vulnerable to...
    validations:
      required: true

  - type: textarea
    id: affected
    attributes:
      label: Affected Components
      description: Which parts of the application are affected?
      placeholder: |
        - File: src/backend/routes/user.js
        - Endpoint: POST /api/v1/users
        - Version: 0.1.0
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the vulnerability
      placeholder: |
        1. Navigate to...
        2. Send a request with...
        3. Observe that...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What is the potential impact of this vulnerability?
      placeholder: |
        An attacker could...
        This would allow...
    validations:
      required: true

  - type: textarea
    id: poc
    attributes:
      label: Proof of Concept
      description: Include proof-of-concept code or HTTP requests (if safe to share)
      placeholder: |
        ```
        curl -X POST ...
        ```

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: If you have suggestions for fixing this, please share them
      placeholder: |
        This could be fixed by...

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to related CVEs, security advisories, or documentation
      placeholder: |
        - https://cve.mitre.org/...
        - https://owasp.org/...

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Please confirm your commitment to responsible disclosure
      options:
        - label: I will not publicly disclose this until a fix is available
          required: true
        - label: I have not shared this information with others
          required: true
